# Where things are
sass:
  sass_dir: _sass
  style: :compresseds

collections:
  pages:
     output: true
     permalink: /:path/

categories_dir: category

# YAML Front Matter defaults
defaults:
  -
    scope:
      path: "_pages"
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:slug/

# Handling Reading
exclude:
  - bower_components # move bower_components content to the appropriate directories (e.g sass, assets, )

# Plugins
gems:
  - jekyll-assets
  - jekyll-paginate

# Pagination
paginate: 5
# paginate_path: "/blog/page:num/"

# Conversion
markdown:    kramdown
highlighter: rouge
# excerpt_separator: "\n\n"

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Serving
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
